name: Deploy Nuxt 3 App

on:
  push:
    branches:
      - main # или любая другая ветка
  workflow_dispatch:

jobs:
  build:
    name: Build Nuxt App
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      - name: Cache npm dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: npm-cache-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            npm-cache-${{ runner.os }}-

      - name: Install dependencies
        run: npm ci

      - name: Build Nuxt App
        run: npx nuxi build

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: nuxt-dist
          path: |
            package.json
            package-lock.json
            ecosystem.config.cjs
            .output
          if-no-files-found: error

  deploy:
    name: Deploy to VPS
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: nuxt-dist
          path: ./nuxt-dist

      - name: Verify artifacts
        run: |
          echo "Содержимое папки с артефактами:"
          ls -la ./nuxt-dist

      - name: Setup SSH
        env:
          SSH_KEY: ${{ secrets.VPS_SSH_KEY }}
          HOST: ${{ secrets.VPS_HOST }}
          USER: ${{ secrets.VPS_USER }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H "$HOST" >> ~/.ssh/known_hosts

      - name: Deploy via rsync
        env:
          HOST: ${{ secrets.VPS_HOST }}
          USER: ${{ secrets.VPS_USER }}
        run: |
          # Копируем содержимое ./nuxt-dist/ в /var/www/stebnev-studio.ru/html
          rsync -avz -e "ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no" --delete ./nuxt-dist/ $USER@$HOST:/var/www/stebnev-studio.ru/html/

          # После копирования перезапускаем pm2
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no $USER@$HOST << 'EOF'
            set -e
            cd /var/www/stebnev-studio.ru/html
            pm2 restart ecosystem.config.cjs --env production || pm2 start ecosystem.config.cjs --env production
            pm2 save
          EOF

      - name: Remove SSH key
        run: rm -f ~/.ssh/id_rsa
