name: Deploy Nuxt 3 App

on:
  push:
    branches:
      - main # Запускать на пуш в ветку main

jobs:
  build:
    name: Build Nuxt App
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"

      - name: Cache npm cache
        uses: actions/cache@v3
        id: npm-cache
        with:
          path: ~/.npm
          key: npm-cache-${{ runner.os }}-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            npm-cache-${{ runner.os }}-

      - name: Install dependencies
        run: npm ci

      - name: Build Nuxt App
        run: npm run build

      - name: List output files
        run: ls -la .output

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: nuxt-dist
          path: |
            .output/**
            package.json
            package-lock.json
            ecosystem.config.cjs
          if-no-files-found: error

  deploy:
    name: Deploy to VPS
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: nuxt-dist
          path: ./nuxt-dist

      - name: Deploy to VPS
        env:
          HOST: ${{ secrets.VPS_HOST }}
          USER: ${{ secrets.VPS_USER }}
          SSH_KEY: ${{ secrets.VPS_SSH_KEY }}
        run: |
          # Создаем директорию .ssh и устанавливаем права
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh

          # Добавляем приватный ключ в файл, сохраняя форматирование
          echo "$SSH_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

          # Добавляем хост в known_hosts
          ssh-keyscan -H "$HOST" >> ~/.ssh/known_hosts

          # Копируем файлы сборки на сервер
          rsync -avz -e "ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no" ./nuxt-dist/ $USER@$HOST:/var/www/stebnev-studio.ru/html/

          # Выполняем команды на сервере для установки зависимостей и перезапуска PM2
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no $USER@$HOST << 'EOF'
            cd /var/www/stebnev-studio.ru/html
            npm ci --production
            pm2 reload ecosystem.config.cjs --env production || pm2 start ecosystem.config.cjs --env production
          EOF

          # Удаляем приватный ключ из runner
          rm -f ~/.ssh/id_rsa
