name: Deploy Nuxt 3 App

on:
  push:
    branches:
      - main # Запускать на пуш в ветку main

jobs:
  build:
    name: Build Nuxt App
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"

      - name: Install dependencies
        run: npm ci

      - name: Build Nuxt App
        run: npm run build

      - name: List output files
        run: ls -la .output

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: nuxt-dist
          path: |
            .output/**
            package.json
            package-lock.json
            ecosystem.config.cjs
          if-no-files-found: error

  deploy:
    name: Deploy to VPS
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: nuxt-dist
          path: ./nuxt-dist

      - name: Install sshpass
        run: |
          sudo apt-get update
          sudo apt-get install sshpass -y
        shell: bash

      - name: Generate SSH Key
        run: |
          ssh-keygen -t ed25519 -f /home/runner/.ssh/deploy_key -N "" -q
          echo "Generated SSH Key:"
          cat /home/runner/.ssh/deploy_key.pub
        shell: bash

      - name: Add SSH Key to Server
        env:
          HOST: ${{ secrets.VPS_HOST }}
          USER: ${{ secrets.VPS_USER }}
          PASSWORD: ${{ secrets.VPS_PASSWORD }}
        run: |
          ssh-keyscan -H "$HOST" >> ~/.ssh/known_hosts
          sshpass -p "$PASSWORD" ssh -o StrictHostKeyChecking=no $USER@$HOST "mkdir -p ~/.ssh && chmod 700 ~/.ssh && echo '$(cat /home/runner/.ssh/deploy_key.pub)' >> ~/.ssh/authorized_keys && chmod 600 ~/.ssh/authorized_keys"
        shell: bash

      - name: Deploy to VPS
        env:
          HOST: ${{ secrets.VPS_HOST }}
          USER: ${{ secrets.VPS_USER }}
        run: |
          rsync -avz -e "ssh -i /home/runner/.ssh/deploy_key -o StrictHostKeyChecking=no" ./nuxt-dist/ $USER@$HOST:/var/www/stebnev-studio.ru/html/
          ssh -i /home/runner/.ssh/deploy_key -o StrictHostKeyChecking=no $USER@$HOST << 'EOF'
            cd /var/www/stebnev-studio.ru/html
            npm ci --production
            pm2 reload ecosystem.config.cjs --env production
          EOF
        shell: bash

      - name: Remove SSH Key from Server
        env:
          HOST: ${{ secrets.VPS_HOST }}
          USER: ${{ secrets.VPS_USER }}
          PASSWORD: ${{ secrets.VPS_PASSWORD }}
        run: |
          sshpass -p "$PASSWORD" ssh -o StrictHostKeyChecking=no $USER@$HOST "grep -v '$(cat /home/runner/.ssh/deploy_key.pub)' ~/.ssh/authorized_keys > ~/.ssh/authorized_keys.tmp && mv ~/.ssh/authorized_keys.tmp ~/.ssh/authorized_keys"
        shell: bash

      - name: Clean up SSH Key
        run: |
          rm -f /home/runner/.ssh/deploy_key /home/runner/.ssh/deploy_key.pub
        shell: bash
