name: Deploy Nuxt 3 App

on:
  push:
    branches:
      - main # Запускать на пуш в ветку main

jobs:
  build:
    name: Build Nuxt App
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"

      - name: Install dependencies
        run: npm ci

      - name: Build Nuxt App
        run: npm run build

      - name: List output files
        run: ls -la .output

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: nuxt-dist
          path: |
            .output/**
            package.json
            package-lock.json
            ecosystem.config.cjs
          if-no-files-found: error

  deploy:
    name: Deploy to VPS
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: nuxt-dist
          path: ./nuxt-dist

      - name: Deploy to VPS
        env:
          HOST: ${{ secrets.VPS_HOST }}
          USER: ${{ secrets.VPS_USER }}
          KEY: ${{ secrets.VPS_SSH_KEY }}
        run: |
          echo "${KEY}" > /tmp/deploy_key
          chmod 600 /tmp/deploy_key

          # Копируем файлы сборки на сервер
          rsync -avz -e "ssh -i /tmp/deploy_key" ./nuxt-dist/ $USER@$HOST:/var/www/stebnev-studio.ru/html/

          # Удаляем временный ключ
          rm -f /tmp/deploy_key

          # Выполняем команды на сервере для установки зависимостей и перезапуска PM2
          ssh -i /tmp/deploy_key $USER@$HOST << 'EOF'
            cd /var/www/stebnev-studio.ru/html
            npm ci --production
            pm2 reload ecosystem.config.cjs --env production
          EOF
